# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{trac4r}
  s.version = "1.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Niklas Cathro", "David Copeland"]
  s.date = %q{2011-07-24}
  s.default_executable = %q{trac}
  s.description = %q{Basic ruby client library and command line interface for accessing Trac instances via its XML RPC API}
  s.email = %q{davidcopeland@naildrivin5.com}
  s.executables = ["trac"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENCE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/trac",
    "lib/trac4r.rb",
    "lib/trac4r/error.rb",
    "lib/trac4r/query.rb",
    "lib/trac4r/ticket.rb",
    "lib/trac4r/tickets.rb",
    "lib/trac4r/wiki.rb"
  ]
  s.rdoc_options = ["--title", "trac4r Trac Ruby Client", "--main", "README.rdoc", "-ri"]
  s.require_paths = ["lib", "lib", "lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Ruby Client Library for Trac}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gli>, [">= 0"])
      s.add_runtime_dependency(%q<rainbow>, [">= 0"])
      s.add_runtime_dependency(%q<grancher>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<sdoc>, [">= 0"])
      s.add_runtime_dependency(%q<rainbow>, [">= 1.0.4"])
      s.add_runtime_dependency(%q<gli>, [">= 1.1.0"])
    else
      s.add_dependency(%q<gli>, [">= 0"])
      s.add_dependency(%q<rainbow>, [">= 0"])
      s.add_dependency(%q<grancher>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sdoc>, [">= 0"])
      s.add_dependency(%q<rainbow>, [">= 1.0.4"])
      s.add_dependency(%q<gli>, [">= 1.1.0"])
    end
  else
    s.add_dependency(%q<gli>, [">= 0"])
    s.add_dependency(%q<rainbow>, [">= 0"])
    s.add_dependency(%q<grancher>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sdoc>, [">= 0"])
    s.add_dependency(%q<rainbow>, [">= 1.0.4"])
    s.add_dependency(%q<gli>, [">= 1.1.0"])
  end
end

